name: GitHub Classroom Workflow

on: [push]
env: 
      BUILD_TYPE: Release 

jobs:
     # build:      
     #       name: build
     #       runs-on: ubuntu-latest
     #       steps:
     #             - uses: actions/checkout@v2
     #             - run : sh build.sh
      tests:
        name: Autograding
        runs-on: ubuntu-latest
        if: ${{github.event.run_number < 2}}
     #   needs: [build]
        steps:
              - name: checkout
                uses: actions/checkout@v2
              - name: build
                run: sh build.sh
              - name: autograding
                uses : education/autograding@v1
              #- name: env
              #  if:  ${{ always() }}
              #  run: env
              - name: upload
                if: ${{always()}}
                uses: actions/upload-artifact@v2
                with:
                  name: report
                  path: report.txt
              - name: report
                # both conditions MUST be insider ${{ }}
                # i leave it here for illustration
                # since it is redundant because >4 condition
                # is set in the job
                if : ${{ always() && github.event.run_number > 4}}
                run: sh report.sh >breakdown.txt
                env:
                 GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
              - name: upload
                if: ${{always()}}
                uses: actions/upload-artifact@v2
                with:
                      name: breakdown
                      path: breakdown.txt
         # - uses: EndBug/add-and-commit@v5
         #   with:
         #      add: "*"
         #   env: 
         #       GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}  
     # status:
     #   name: status
     #   runs-on: ubuntu-latest
     #   needs: [tests]
        #if: "!contains(github.event.head_commit.message, 'GitHub')"
        # for some reason the below does not work
        #if: "!contains(github.event.actor,'github-classroom')"
     #   if : github.event.run_number > 4
     #   steps:
     #      - name: checkout
     #        uses: actions/checkout@v2
     #         #- name: environ
     #         #  run: env
      #     - name: download
      #       uses: actions/download-artifact@v2
      #       with:
      #          name: report
      #     - name: status
      #       run: sh status.sh
      #       env:
      #            GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
              
