name: Build MacOs
on: [push]
env: 
      BUILD_TYPE: Release 

jobs:
      tests:
        name: macOS-build
        runs-on: macos-latest
        steps:
             
              - name: checkout
                uses: actions/checkout@v2
              - name: build
                run: |
                  cmake -G Xcode -S . -B build
                  cmake --build build/ --target test0
                  ls build
              - name: upload
                uses: actions/upload-artifact@v2
                with:
                      name: breakdown
                      path: build/csc413-hw0.xcodeproj

       
